services:
  tictactoeapp:
    container_name: tictactoeapp
    build:
      context: .
      dockerfile: build/Dockerfile
    ports:
      - "6000:8080"
    restart: always
    healthcheck:
      test: curl -fsS localhost:8080/ping
    volumes:
      - ./web:/web
